a = input('digite algo: ')
print('O tipo primitivo desse valor é: ', type(a))
print('So tem espaço? ', a.isspace())
print('É um número? ', a.isnumeric())
print('É alfabético? ', a.isalpha())
print('É alfanumerico? ', a.isalnum())
print('Esta em maiuscula? ', a.isupper())
print('esta em minuscula? ', a.islower())
print('Está capitalizada? ', a.istitle())